#!/usr/bin/env bash

# Kijk of het bestand 'filelinks' bestaat
if [ -a filelinks ]; then
	# Uitleg indien geen input
	if [ -d $1 ]; then
		echo -e "\n\tVoer een rooster- of docentcode in
				 \n\tVoorbeeld: ./rooster hps\n"
		exit 1
	fi

	# Variables
	REGEX="MINGW(32|64)\_NT"
	 KLAS=$(cat filelinks | grep -i $1 | head -1 | cut -f1 -d ",")
	  URL=$(cat filelinks | grep -i $1 | head -1 | cut -f2 -d ",")

	# Kijken of het rooster is gevonden
	if [ -z $URL ]; then
		echo -e "\n\tRooster- of docentcode niet gevonden!\n"
	else
		# Alles gelukt: open het rooster
		echo -e "\n\tHet rooster van ${KLAS} openen\n"
		if [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
			xdg-open $URL
		elif [[ "$(expr substr $(uname -s) 1 10)" =~ $REGEX ]]; then
			start $URL
		elif [[ "$(uname)" == "Darwin" ]]; then
			open $URL
			exit 1
		fi
	fi
else
	echo -e "\n\tBestand met URLs niet gevonden!\n"
fi
