#!/bin/bash

##Check of bestand met URL's bestaat
if [ -a filelinks ]; then
  ## Check of input leeg is
  if [ -d $1 ]; then
    echo 'Voer een docentcode in'
    echo './rooster hps'
    exit 1
  fi

  ## Zetten variabele docentcode en url
  export DOCENT=$(echo $1 | awk '{print toupper($0)}')
  export URL=$(cat filelinks  | grep $DOCENT | cut -f2 -d ",")

  ## Opent $URL in standaardbrowser
  echo 'Opent rooster van' $DOCENT
  xdg-open $URL
  exit 1

else
  echo 'Bestand met urls niet gevonden'

fi
